name: Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.14t]

    services:
      http:
        options: --name http
        image: ghcr.io/astral-sh/uv:debian-slim
        env:
          UV_PYTHON: 3.14
        entrypoint: uvx
        command: --from granian granian --working-dir /app --host 0.0.0.0 http_server:app
        ports:
        - 8000:8000
        volumes:
        - ${{ github.workspace }}/dmnt:/app

      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
        - 5432:5432

      redis:
        image: redis:8-alpine
        ports:
        - 6379:6379

    env:
      TM_HTTPX_ENDPOINT: http://127.0.0.1:8000/echo
      TM_PSYCOPG_DSN: postgresql://postgres:postgres@localhost:5432/test
      TM_REDIS_DSN: redis://@127.0.0.1:6379/0
      TM_WS_ENDPOINT: ws://127.0.0.1:8000/ws

    steps:
    - uses: actions/checkout@v7
    - run: cp -r tests/_utils dmnt/
    - uses: docker://docker
      with:
        args: docker restart http
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ matrix.python-version }}
        uv venv .venv
        uv sync --all-extras --group test
    - name: Test
      run: |
        uv run pytest -v tests
